spring:
  cloud:
    stream:
      defaultBinder: kafka
      kafka.binder:
        zkNodes: localhost:2181
        brokers: localhost:9092
        headers: [CORRELATION_ID, x-newrelic-id, x-newrelic-transaction]
      bindings:
        output:
          destination: hello


server:
  port: 8081
