spring:
  cloud:
    stream:
      defaultBinder: kafka
      kafka.binder:
        zkNodes: localhost:2181
        brokers: localhost:9092
        headers: [CORRELATION_ID]
      bindings:
        output:
          destination: hello

logging:
  pattern:
    console: "%d [%X{CORRELATION_ID}] [%thread] %-5level %logger : %msg%n"

server:
  port: 8081
