server:
  port: 8082

spring:
  cloud:
    stream:
      defaultBinder: kafka
      kafka.binder:
        zkNodes: localhost:2181
        brokers: localhost:9092
        headers: [CORRELATION_ID]
      bindings:
        input:
          destination: hello