server:
  port: 8082

spring:
  cloud:
    stream:
      kafka.binder:
        zkNodes: ${ZOOKEEPER_ENDPOINT:localhost:2181}
        brokers: ${KAFKABROKER_ENDPOINT:localhost:9092}
      output:
        destination: hello